#!/usr/bin/env python3
from __future__ import annotations

import csv
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "results" / "all_runs.csv"
OUT_PATH = ROOT / "docs" / "benchmark_report.md"


def load_rows() -> list[dict[str, str]]:
    if not CSV_PATH.exists():
        print(f"missing {CSV_PATH}; run bench/run_all.sh first", file=sys.stderr)
        sys.exit(1)
    with CSV_PATH.open() as f:
        return list(csv.DictReader(f))


def section(title: str, labels: list[str], rows: list[dict[str, str]]) -> str:
    selected = [r for r in rows if r["label"] in labels]
    if not selected:
        return f"## {title}\n\n_(no data)_\n\n"
    cols = ["label", "ticks", "min_ns", "mean_ns", "p50_ns", "p95_ns", "p99_ns", "max_ns"]
    out = [f"## {title}", ""]
    out.append("| " + " | ".join(cols) + " |")
    out.append("|" + "|".join(["---"] * len(cols)) + "|")
    for r in selected:
        out.append("| " + " | ".join(r[c] for c in cols) + " |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    rows = load_rows()
    parts = [
        "# Phase 4 Benchmark Report",
        "",
        "_Generated by `scripts/render_report.py` from `results/all_runs.csv`._",
        "",
        section("Pointer ownership (unique_ptr vs raw)", ["reference", "raw-ptr"], rows),
        section("Cache alignment (alignas(64) on/off)", ["reference", "no-align"], rows),
        section("Allocator (pool vs new/delete)", ["reference", "no-pool"], rows),
        section("Book container (flat vector vs multimap)", ["reference", "book-mmap"], rows),
        section("Load scaling (1k/10k/100k ticks)", ["load-1k", "load-10k", "load-100k"], rows),
        "## Notes",
        "",
        "- All numbers in nanoseconds.",
        "- `HFT_USE_RAW_PTR` does not currently change order storage (OMS uses shared_ptr per spec). The row is included for completeness.",
        "- Run on Apple Silicon, Release build (`-O3 -march=native -flto`), single-threaded.",
        "",
    ]
    OUT_PATH.write_text("\n".join(parts))
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
